[tool.poetry]
name = "motor-server-local"
version = "0.1.0"
description = "Servidor local para simular velocidad y temperatura de un motor"
authors = ["Carlos"]
packages = [{ include = "motor_server" }]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.110"
uvicorn = "^0.29"
cryptography = "^42.0"

[tool.poetry.scripts]
motor-server = "motor_server.app:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
